export default {
  import: ["@cspell/dict-lorem-ipsum/cspell-ext.json"],
  caseSensitive: false,
  dictionaries: ["dictionary"],
  dictionaryDefinitions: [
    {
      name: "dictionary",
      path: "./.cspell/dictionary.txt",
      addWords: true,
    },
  ],
  ignorePaths: [
    "**/node_modules/**",
    "**/dist/**",
    "**/build/**",
    "**/lib/**",
    "**/docs/**",
    "**/vendor/**",
    "**/public/**",
    "**/static/**",
    "**/out/**",
    "**/tmp/**",
    "**/*.d.ts",
    "**/*.yaml",
    "**/package.json",
    "**/tsconfig.json",
    "**/*.md",
    "**/stats.html",
    ".cspell",
    ".husky",
    ".gitignore",
    ".prettierignore",
    ".npmrc",
    "commitlint.config.ts",
    "cspell.config.ts",
    "eslint.config.ts",
    ".lint-stage.config.ts",
  ],
}
